language: go

go:
  - 1.4.3
  - 1.5.3


install:
  - go get -t -v ./messaging/
  - ln -s $GOPATH/src/github.com/pubnub/go $GOPATH/src/github.com/anovikov1984/go
script:
  - cd messaging && go test
  - cd tests && go test
