language: go

go:
  - 1.5

install:
  - go get -t -v ./messaging/
  - mkdir -p $GOPATH/src/github.com/pubnub
  - ln -s $GOPATH/src/github.com/anovikov1984/go $GOPATH/src/github.com/pubnub/go

script:
  - cd messaging/tests && go test -v -race common.go pubnubDetailedHistory_test.go
