language: go

go:
  - 1.4.3
  - 1.5.3


before_script: 
  - ln -s $(GOPATH)/src/github.com/pubnub/go $(GOPATH)/src/github.com/anovikov1984/go
install: go get -t -v ./messaging/
script:
  - cd messaging && go test
  - cd tests && go test
