language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6

install:
  - mkdir -p $GOPATH/src/github.com/pubnub
  - ln -s $GOPATH/src/github.com/anovikov1984/go $GOPATH/src/github.com/pubnub/go
  - go get -t -v ./messaging/...

script:
  - cd messaging && go test -v -race
  - cd tests && go test -v -race
